### ISSUE TITLE
Barber::PrecompilerError in Neo4j::MetaModel::Models#meta_index

### ISSUE THREAD

**Issue by djvs** [neo4jrb/neo4j-meta_model#6]
Showing /home/me/.rvm/gems/ruby-2.2.0/gems/neo4j-meta_model-0.3.2/app/views/layouts/meta_model.html.slim where line #10 raised:

    Pre compilation failed for: div.list-group
      each child in node
        model-list-item model=child.[0] sub_hierarchy=child.[1]

    . Compiler said: TypeError: Cannot read property 'original' of undefined
      (in /home/me/.rvm/gems/ruby-2.2.0/gems/neo4j-meta_model-0.3.2/app/assets/javascripts/templates/components/model-list.emblem)

    Extracted source (around line #15):
    13      context.call precompile_function, sanitize(template)
    14    rescue ExecJS::ProgramError => ex
    15      raise Barber::PrecompilerError.new(template, ex)
    16    end
    17    
    18    def precompile_function

**Comment by cheerfulstoic** [comment]
It seems to be an issue with dependencies.  I can get it to work when I load the gem from my local directory, but when I try to load from github or rubygems it gets this error.  Will look more later

**Comment by ernestoe** [comment]
Having the same issue, it used to work in the past.

**Comment by cheerfulstoic** [comment]
I just released version **0.4.0**.  Try that and see if it works.  Since there was so much trouble with the various gems that I depended on (like `ember-rails`) I recently did some work to refactor it to use `ember-cli`.

**Comment by ernestoe** [comment]
I get a "undefined method `hierarchical_render' for #<#Class:0x007f897e412760:0x007f897e411770>"  in neo4j-meta_model (0.4.0) app/views/neo4j/meta_model/models/meta_index.html.slim, however I'm not sure whether this is related to existing data in my database. Tried the neo4j-meta_model-app, updated the gems and now this is working although there are quite a few glitches while using the admin views. Selecting from the "many" relationships doesn't seem to be working either. I mention here as I'm not sure whether this is also related to the gem dependencies, I'll try to follow into those independently. Thanks for the work, looking at this will allow me to have a better understanding of the neo4jrb project all together.

**Comment by cheerfulstoic** [comment]
Sorry, I know it's a bit raw.  I haven't had as much time to work on it as I'd like ;)  If you have any other problems feel free to open an issue, though I will be on holiday until around June 2nd

**Comment by ernestoe** [comment]
No need to be sorry, I'll open the issue while I check on the code as well. Enjoy your holidays.
