### ISSUE TITLE
undefined method `hierarchical_render' for class

### ISSUE THREAD

**Issue by ernestoe** [neo4jrb/neo4j-meta_model#7]
I get a "undefined method `hierarchical_render' for #<#Class:0x007f897e412760:0x007f897e411770>" in neo4j-meta_model (0.4.0) app/views/neo4j/meta_model/models/meta_index.html.slim, when integrating the gem to an existing project. It works fine in the stand-alone app neo4j-meta_model-app . I'm reusing the same database for both scenarios.

**Comment by subvertallchris** [comment]
I think @cheerfulstoic is gonna be away for a few days, so proper response here might be a little slow. As soon as he's around, he'll get back to you, so please hang tight!

**Comment by cheerfulstoic** [comment]
Thanks for the feedback!  Sorry for the delay, I just got back from holiday.

I'm not exactly sure why that would be.  Some questions:
- What version of rails are you using?
- Can you share the full stack trace?
- Does this happen with a new rails app?

**Comment by subvertallchris** [comment]
Btw, I'm unable to reproduce this. Tried with MRI 2.2.2 and JRuby 1.7.18
with Embedded.

**Comment by ernestoe** [comment]
Hello back.

After your comments I went back to experiment and discovered this only happens when combined with the rack-mini-profiler gem that I'm using in order to do some profiling.

When commenting out this gem the problem goes away.

I'll be doing some other tests throughout the week and let you know.

**Comment by cheerfulstoic** [comment]
Ah, interesting, thanks!  Please do let me know.  It seems like rack-mini-profiler might also be a Rails engine, so that might be part of the problem.
